FROM node:22-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

# Этап сборки
FROM node:22-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN mkdir -p ./public
ARG NEXT_PUBLIC_PORT
ARG NEXT_PUBLIC_SERVER_HOST
ARG NEXT_PUBLIC_PRODUCTION_HOST
ARG NEXT_PUBLIC_API_PATH
ARG NEXT_PUBLIC_STORAGE_KEY
ARG NEXT_PUBLIC_LANGUAGE_KEY
ARG NEXT_PUBLIC_NEW_ITEM_STORAGE_KEY
ARG NEXT_PUBLIC_URL_PERSONAL_TG_ACCOUNT
ARG NEXT_PUBLIC_URL_TG_ACCOUNT
ARG NEXT_PUBLIC_URL_INST_ACCOUNT
ARG NEXT_PUBLIC_APP_NAME
ARG NEXT_PUBLIC_WORK_PHONE
ARG NEXT_PUBLIC_CONTACT_MAIL
ARG NEXT_PUBLIC_FIO
ARG NEXT_PUBLIC_FIO_EN
ARG NEXT_PUBLIC_INN
ARG NEXT_PUBLIC_PROMO

ENV NEXT_PUBLIC_PORT=$NEXT_PUBLIC_PORT
ENV NEXT_PUBLIC_SERVER_HOST=$NEXT_PUBLIC_SERVER_HOST
ENV NEXT_PUBLIC_PRODUCTION_HOST=$NEXT_PUBLIC_PRODUCTION_HOST
ENV NEXT_PUBLIC_API_PATH=$NEXT_PUBLIC_API_PATH
ENV NEXT_PUBLIC_STORAGE_KEY=$NEXT_PUBLIC_STORAGE_KEY
ENV NEXT_PUBLIC_LANGUAGE_KEY=$NEXT_PUBLIC_LANGUAGE_KEY
ENV NEXT_PUBLIC_NEW_ITEM_STORAGE_KEY=$NEXT_PUBLIC_NEW_ITEM_STORAGE_KEY
ENV NEXT_PUBLIC_URL_PERSONAL_TG_ACCOUNT=$NEXT_PUBLIC_URL_PERSONAL_TG_ACCOUNT
ENV NEXT_PUBLIC_URL_TG_ACCOUNT=$NEXT_PUBLIC_URL_TG_ACCOUNT
ENV NEXT_PUBLIC_URL_INST_ACCOUNT=$NEXT_PUBLIC_URL_INST_ACCOUNT
ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME
ENV NEXT_PUBLIC_WORK_PHONE=$NEXT_PUBLIC_WORK_PHONE
ENV NEXT_PUBLIC_CONTACT_MAIL=$NEXT_PUBLIC_CONTACT_MAIL
ENV NEXT_PUBLIC_FIO=$NEXT_PUBLIC_FIO
ENV NEXT_PUBLIC_FIO_EN=$NEXT_PUBLIC_FIO_EN
ENV NEXT_PUBLIC_INN=$NEXT_PUBLIC_INN
ENV NEXT_PUBLIC_PROMO=$NEXT_PUBLIC_PROMO

RUN npm run build

# Финальный образ
FROM node:22-alpine AS app
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY --from=builder /app/cron ./cron
COPY --from=builder /app/server ./server
COPY --from=builder /app/microservices/sender ./microservices/sender
COPY --from=builder /app/src ./src
COPY --from=builder /app/package.json ./
COPY --from=builder /app/tsconfig.json ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
EXPOSE 3010

# Устанавливаем ENTRYPOINT для npm, чтобы CMD определял конкретный скрипт
ENTRYPOINT ["npm", "run"]