import { YandexDeliveryStatusEnum } from '@server/types/delivery/yandex/enums/yandex.delivery.status.enum';
import { UserLangEnum } from '@server/types/user/enums/user.lang.enum';

export const yandexDeliveryTranslateStatus: Record<UserLangEnum, Record<YandexDeliveryStatusEnum, string>> = {
  [UserLangEnum.RU]: {
    [YandexDeliveryStatusEnum.DRAFT]: 'Заказ создан',
    [YandexDeliveryStatusEnum.VALIDATING]: 'Заявка находится на проверке',
    [YandexDeliveryStatusEnum.VALIDATING_ERROR]: 'Заказ не подтвержден в сортировочном центре',
    [YandexDeliveryStatusEnum.CREATED]: 'Заказ создан и подтвержден',
    [YandexDeliveryStatusEnum.DELIVERY_PROCESSING_STARTED]: 'Заказ создается в сортировочном центре',
    [YandexDeliveryStatusEnum.DELIVERY_TRACK_RECEIVED]: 'Заказ создан в системе службы доставки',
    [YandexDeliveryStatusEnum.SORTING_CENTER_PROCESSING_STARTED]: 'Заказ начал обрабатываться в сортировочном центре',
    [YandexDeliveryStatusEnum.SORTING_CENTER_TRACK_RECEIVED]: 'Заказ обработан в сортировочном центре',
    [YandexDeliveryStatusEnum.SORTING_CENTER_TRACK_LOADED]: 'Заказ создан в сортировочном сортировочном центре',
    [YandexDeliveryStatusEnum.DELIVERY_LOADED]: 'Заказ добавлен в текущую ОТГРУЗКУ',
    [YandexDeliveryStatusEnum.SORTING_CENTER_LOADED]: 'Заказ подтвержден в сортировочном центре',
    [YandexDeliveryStatusEnum.SORTING_CENTER_AT_START]: 'Заказ поступил в сортировочный центр',
    [YandexDeliveryStatusEnum.SORTING_CENTER_PREPARED]: 'Заказ готов к отправке в службу доставки',
    [YandexDeliveryStatusEnum.SORTING_CENTER_TRANSMITTED]: 'Заказ доставляется',
    [YandexDeliveryStatusEnum.DELIVERY_AT_START]: 'Заказ готовится к отправке получателю',
    [YandexDeliveryStatusEnum.DELIVERY_TRANSPORTATION]: 'Заказ выехал в пункт назначения',
    [YandexDeliveryStatusEnum.DELIVERY_ARRIVED_PICKUP_POINT]: 'Заказ доставлен в пункт назначения',
    [YandexDeliveryStatusEnum.DELIVERY_TRANSMITTED_TO_RECIPIENT]: 'Заказ выдан получателю',
    [YandexDeliveryStatusEnum.DELIVERY_STORAGE_PERIOD_EXPIRED]: 'Срок хранения заказа в точке выдачи истек',
    [YandexDeliveryStatusEnum.DELIVERY_STORAGE_PERIOD_EXTENDED]: 'Срок хранения заказа в точке выдачи продлен',
    [YandexDeliveryStatusEnum.CONFIRMATION_CODE_RECEIVED]: 'Получен код подтверждения заказа',
    [YandexDeliveryStatusEnum.PARTICULARLY_DELIVERED]: 'Заказ частично доставлен',
    [YandexDeliveryStatusEnum.DELIVERY_DELIVERED]: 'Заказ доставлен получателю',
    [YandexDeliveryStatusEnum.FINISHED]: 'Заказ подтвержден',
  },
  [UserLangEnum.EN]: {
    [YandexDeliveryStatusEnum.DRAFT]: 'Draft',
    [YandexDeliveryStatusEnum.VALIDATING]: 'Validating',
    [YandexDeliveryStatusEnum.VALIDATING_ERROR]: 'Validating error',
    [YandexDeliveryStatusEnum.CREATED]: 'Created',
    [YandexDeliveryStatusEnum.DELIVERY_PROCESSING_STARTED]: 'Delivery processing started',
    [YandexDeliveryStatusEnum.DELIVERY_TRACK_RECEIVED]: 'Delivery track received',
    [YandexDeliveryStatusEnum.SORTING_CENTER_PROCESSING_STARTED]: 'Sorting center processing started',
    [YandexDeliveryStatusEnum.SORTING_CENTER_TRACK_RECEIVED]: 'Sorting center track received',
    [YandexDeliveryStatusEnum.SORTING_CENTER_TRACK_LOADED]: 'Sorting center track loaded',
    [YandexDeliveryStatusEnum.DELIVERY_LOADED]: 'Delivery loaded',
    [YandexDeliveryStatusEnum.SORTING_CENTER_LOADED]: 'Sorting center loaded',
    [YandexDeliveryStatusEnum.SORTING_CENTER_AT_START]: 'Sorting center at start',
    [YandexDeliveryStatusEnum.SORTING_CENTER_PREPARED]: 'Sorting center prepared',
    [YandexDeliveryStatusEnum.SORTING_CENTER_TRANSMITTED]: 'Sorting center transmitted',
    [YandexDeliveryStatusEnum.DELIVERY_AT_START]: 'Delivery at start',
    [YandexDeliveryStatusEnum.DELIVERY_TRANSPORTATION]: 'Delivery transportation',
    [YandexDeliveryStatusEnum.DELIVERY_ARRIVED_PICKUP_POINT]: 'Delivery arrived pickup point',
    [YandexDeliveryStatusEnum.DELIVERY_TRANSMITTED_TO_RECIPIENT]: 'Delivery transmitted to recipient',
    [YandexDeliveryStatusEnum.DELIVERY_STORAGE_PERIOD_EXPIRED]: 'Delivery storage period expired',
    [YandexDeliveryStatusEnum.DELIVERY_STORAGE_PERIOD_EXTENDED]: 'Delivery storage period extended',
    [YandexDeliveryStatusEnum.CONFIRMATION_CODE_RECEIVED]: 'Confirmation code received',
    [YandexDeliveryStatusEnum.PARTICULARLY_DELIVERED]: 'Particularly delivered',
    [YandexDeliveryStatusEnum.DELIVERY_DELIVERED]: 'Delivery delivered',
    [YandexDeliveryStatusEnum.FINISHED]: 'Finished',
  },
};
