export enum BullMQQueuesEnum {
  SMS_CODE_QUEUE = 'SMS_CODE_QUEUE',
  SMS_PASSWORD_QUEUE = 'SMS_PASSWORD_QUEUE',
  TELEGRAM_QUEUE = 'TELEGRAM_QUEUE',
  TELEGRAM_ADMIN_QUEUE = 'TELEGRAM_ADMIN_QUEUE',
  CDEK_DELIVERY_QUEUE = 'CDEK_DELIVERY_QUEUE',
}
