import { CDEKDeliveryStatusEnum } from '@server/types/delivery/cdek/enums/cdek-delivery-status.enum';
import { UserLangEnum } from '@server/types/user/enums/user.lang.enum';

export const CDEKDeliveryTranslateStatus: Record<UserLangEnum, Record<CDEKDeliveryStatusEnum, string>> = {
  [UserLangEnum.RU]: {
    [CDEKDeliveryStatusEnum.CREATED]: 'Создан',
    [CDEKDeliveryStatusEnum.REMOVED]: 'Удалён',
    [CDEKDeliveryStatusEnum.RECEIVED_AT_SHIPMENT_WAREHOUSE]: 'Принят на склад отправителя',
    [CDEKDeliveryStatusEnum.READY_TO_SHIP_AT_SENDING_OFFICE]: 'Выдан на отправку в г. отправителе',
    [CDEKDeliveryStatusEnum.READY_FOR_SHIPMENT_IN_TRANSIT_CITY]: 'Выдан на отправку в г. отправителе',
    [CDEKDeliveryStatusEnum.RETURNED_TO_SENDER_CITY_WAREHOUSE]: 'Возвращён на склад отправителя',
    [CDEKDeliveryStatusEnum.PASSED_TO_CARRIER_AT_SENDING_OFFICE]: 'Сдан перевозчику в г. отправителе',
    [CDEKDeliveryStatusEnum.SEND_TO_TRANSIT_OFFICE]: 'Отправлен в г. транзит',
    [CDEKDeliveryStatusEnum.MET_AT_TRANSIT_OFFICE]: 'Встречен в г. транзите',
    [CDEKDeliveryStatusEnum.ACCEPTED_AT_TRANSIT_WAREHOUSE]: 'Принят на склад транзита',
    [CDEKDeliveryStatusEnum.RETURNED_TO_TRANSIT_WAREHOUSE]: 'Возвращен на склад транзита',
    [CDEKDeliveryStatusEnum.READY_TO_SHIP_IN_TRANSIT_OFFICE]: 'Выдан на отправку в г. транзите',
    [CDEKDeliveryStatusEnum.PASSED_TO_CARRIER_AT_TRANSIT_OFFICE]: 'Сдан перевозчику в г. транзите',
    [CDEKDeliveryStatusEnum.SENT_TO_SENDER_CITY]: 'Отправлен в г. отправитель',
    [CDEKDeliveryStatusEnum.MET_AT_SENDING_OFFICE]: 'Встречен в г. отправителе',
    [CDEKDeliveryStatusEnum.MET_AT_RECIPIENT_OFFICE]: 'Встречен в г. получателе',
    [CDEKDeliveryStatusEnum.ACCEPTED_AT_RECIPIENT_CITY_WAREHOUSE]: 'Принят на склад доставки',
    [CDEKDeliveryStatusEnum.ACCEPTED_AT_PICK_UP_POINT]: 'Доставлено в пункт выдачи',
    [CDEKDeliveryStatusEnum.TAKEN_BY_COURIER]: 'Выдан на доставку',
    [CDEKDeliveryStatusEnum.RETURNED_TO_RECIPIENT_CITY_WAREHOUSE]: 'Возвращен на склад доставки',
    [CDEKDeliveryStatusEnum.DELIVERED]: 'Вручен',
    [CDEKDeliveryStatusEnum.NOT_DELIVERED]: 'Не вручен',
    [CDEKDeliveryStatusEnum.ENTERED_TO_OFFICE_TRANSIT_WAREHOUSE]: 'Поступил в г. транзита',
    [CDEKDeliveryStatusEnum.ENTERED_TO_DELIVERY_WAREHOUSE]: 'Поступил на склад доставки',
    [CDEKDeliveryStatusEnum.ENTERED_TO_WAREHOUSE_ON_DEMAND]: 'Поступил на склад до востребования',
    [CDEKDeliveryStatusEnum.IN_CUSTOMS_INTERNATIONAL]: 'Таможенное оформление в стране отправления',
    [CDEKDeliveryStatusEnum.SHIPPED_TO_DESTINATION]: 'Отправлено в страну назначения',
    [CDEKDeliveryStatusEnum.PASSED_TO_TRANSIT_CARRIER]: 'Передано транзитному перевозчику',
    [CDEKDeliveryStatusEnum.IN_CUSTOMS_LOCAL]: 'Таможенное оформление в стране назначения',
    [CDEKDeliveryStatusEnum.CUSTOMS_COMPLETE]: 'Таможенное оформление завершено',
    [CDEKDeliveryStatusEnum.POSTOMAT_POSTED]: 'Заложен в постамат',
    [CDEKDeliveryStatusEnum.POSTOMAT_SEIZED]: 'Изъят из постамата курьером',
    [CDEKDeliveryStatusEnum.POSTOMAT_RECEIVED]: 'Изъят из постамата клиентом',
    [CDEKDeliveryStatusEnum.READY_FOR_SHIPMENT_IN_SENDER_CITY]: 'Готов к отправке в городе отправителе',
    [CDEKDeliveryStatusEnum.TAKEN_BY_TRANSPORTER_FROM_SENDER_CITY]: 'Сдан перевозчику в городе отправителе',
    [CDEKDeliveryStatusEnum.SENT_TO_TRANSIT_CITY]: 'Отправлен в город-транзит',
    [CDEKDeliveryStatusEnum.ACCEPTED_IN_TRANSIT_CITY]: 'Встречен в городе-транзите',
    [CDEKDeliveryStatusEnum.TAKEN_BY_TRANSPORTER_FROM_TRANSIT_CITY]: 'Сдан перевозчику в городе-транзите',
    [CDEKDeliveryStatusEnum.SENT_TO_RECIPIENT_CITY]: 'Отправлен в город-получатель',
    [CDEKDeliveryStatusEnum.ACCEPTED_IN_RECIPIENT_CITY]: 'Встречен в городе-получателе',
  },
  [UserLangEnum.EN]: {
    [CDEKDeliveryStatusEnum.CREATED]: 'Created',
    [CDEKDeliveryStatusEnum.REMOVED]: 'Removed',
    [CDEKDeliveryStatusEnum.RECEIVED_AT_SHIPMENT_WAREHOUSE]: 'Received at shipment warehouse',
    [CDEKDeliveryStatusEnum.READY_TO_SHIP_AT_SENDING_OFFICE]: 'Ready to ship at sending office',
    [CDEKDeliveryStatusEnum.READY_FOR_SHIPMENT_IN_TRANSIT_CITY]: 'Ready for shipment in transit city',
    [CDEKDeliveryStatusEnum.RETURNED_TO_SENDER_CITY_WAREHOUSE]: 'Returned to sender city warehouse',
    [CDEKDeliveryStatusEnum.PASSED_TO_CARRIER_AT_SENDING_OFFICE]: 'Passed to carrier at sending office',
    [CDEKDeliveryStatusEnum.SEND_TO_TRANSIT_OFFICE]: 'Send to transit office',
    [CDEKDeliveryStatusEnum.MET_AT_TRANSIT_OFFICE]: 'Met at transit office',
    [CDEKDeliveryStatusEnum.ACCEPTED_AT_TRANSIT_WAREHOUSE]: 'Accepted at transit warehouse',
    [CDEKDeliveryStatusEnum.RETURNED_TO_TRANSIT_WAREHOUSE]: 'Returned to transit warehouse',
    [CDEKDeliveryStatusEnum.READY_TO_SHIP_IN_TRANSIT_OFFICE]: 'Ready to ship in transit office',
    [CDEKDeliveryStatusEnum.PASSED_TO_CARRIER_AT_TRANSIT_OFFICE]: 'Passed to carrier at transit office',
    [CDEKDeliveryStatusEnum.SENT_TO_SENDER_CITY]: 'Sent to sender city',
    [CDEKDeliveryStatusEnum.MET_AT_SENDING_OFFICE]: 'Met at sending office',
    [CDEKDeliveryStatusEnum.MET_AT_RECIPIENT_OFFICE]: 'Met at recipient office',
    [CDEKDeliveryStatusEnum.ACCEPTED_AT_RECIPIENT_CITY_WAREHOUSE]: 'Accepted at recipient city warehouse',
    [CDEKDeliveryStatusEnum.ACCEPTED_AT_PICK_UP_POINT]: 'Delivered to the pick-up point',
    [CDEKDeliveryStatusEnum.TAKEN_BY_COURIER]: 'Taken by courier',
    [CDEKDeliveryStatusEnum.RETURNED_TO_RECIPIENT_CITY_WAREHOUSE]: 'Returned to recipient city warehouse',
    [CDEKDeliveryStatusEnum.DELIVERED]: 'Delivered',
    [CDEKDeliveryStatusEnum.NOT_DELIVERED]: 'Not delivered',
    [CDEKDeliveryStatusEnum.ENTERED_TO_OFFICE_TRANSIT_WAREHOUSE]: 'Entered to office transit warehouse',
    [CDEKDeliveryStatusEnum.ENTERED_TO_DELIVERY_WAREHOUSE]: 'Entered to delivery warehouse',
    [CDEKDeliveryStatusEnum.ENTERED_TO_WAREHOUSE_ON_DEMAND]: 'Entered to warehouse on demand',
    [CDEKDeliveryStatusEnum.IN_CUSTOMS_INTERNATIONAL]: 'In customs international',
    [CDEKDeliveryStatusEnum.SHIPPED_TO_DESTINATION]: 'Shipped to destination',
    [CDEKDeliveryStatusEnum.PASSED_TO_TRANSIT_CARRIER]: 'Passed to transit carrier',
    [CDEKDeliveryStatusEnum.IN_CUSTOMS_LOCAL]: 'In customs local',
    [CDEKDeliveryStatusEnum.CUSTOMS_COMPLETE]: 'Customs complete',
    [CDEKDeliveryStatusEnum.POSTOMAT_POSTED]: 'Postomat posted',
    [CDEKDeliveryStatusEnum.POSTOMAT_SEIZED]: 'Postomat seized',
    [CDEKDeliveryStatusEnum.POSTOMAT_RECEIVED]: 'Postomat received',
    [CDEKDeliveryStatusEnum.READY_FOR_SHIPMENT_IN_SENDER_CITY]: 'Ready for shipment in sender city',
    [CDEKDeliveryStatusEnum.TAKEN_BY_TRANSPORTER_FROM_SENDER_CITY]: 'Taken by transporter from sender city',
    [CDEKDeliveryStatusEnum.SENT_TO_TRANSIT_CITY]: 'Sent to transit city',
    [CDEKDeliveryStatusEnum.ACCEPTED_IN_TRANSIT_CITY]: 'Accepted in transit city',
    [CDEKDeliveryStatusEnum.TAKEN_BY_TRANSPORTER_FROM_TRANSIT_CITY]: 'Taken by transporter from transit city',
    [CDEKDeliveryStatusEnum.SENT_TO_RECIPIENT_CITY]: 'Sent to recipient city',
    [CDEKDeliveryStatusEnum.ACCEPTED_IN_RECIPIENT_CITY]: 'Accepted in recipient city',
  },
};
