import { YandexDeliveryStatusEnum } from '@server/types/delivery/enums/yandex/yandex.delivery.status.enum';

export const yandexDeliveryTranslateStatus: Record<YandexDeliveryStatusEnum, string> = {
  [YandexDeliveryStatusEnum.DRAFT]: 'Заказ создан',
  [YandexDeliveryStatusEnum.VALIDATING]: 'Заявка находится на проверке',
  [YandexDeliveryStatusEnum.VALIDATING_ERROR]: 'Заказ не подтвержден в сортировочном центре',
  [YandexDeliveryStatusEnum.CREATED]: 'Заказ создан и подтвержден',
  [YandexDeliveryStatusEnum.DELIVERY_PROCESSING_STARTED]: 'Заказ создается в сортировочном центре',
  [YandexDeliveryStatusEnum.DELIVERY_TRACK_RECEIVED]: 'Заказ создан в системе службы доставки',
  [YandexDeliveryStatusEnum.SORTING_CENTER_PROCESSING_STARTED]: 'Заказ начал обрабатываться в сортировочном центре',
  [YandexDeliveryStatusEnum.SORTING_CENTER_TRACK_RECEIVED]: 'Заказ обработан в сортировочном центре',
  [YandexDeliveryStatusEnum.SORTING_CENTER_TRACK_LOADED]: 'Заказ создан в сортировочном сортировочном центре',
  [YandexDeliveryStatusEnum.DELIVERY_LOADED]: 'Заказ добавлен в текущую ОТГРУЗКУ',
  [YandexDeliveryStatusEnum.SORTING_CENTER_LOADED]: 'Заказ подтвержден в сортировочном центре',
  [YandexDeliveryStatusEnum.SORTING_CENTER_AT_START]: 'Заказ поступил в сортировочный центр',
  [YandexDeliveryStatusEnum.SORTING_CENTER_PREPARED]: 'Заказ готов к отправке в службу доставки',
  [YandexDeliveryStatusEnum.SORTING_CENTER_TRANSMITTED]: 'Заказ доставляется',
  [YandexDeliveryStatusEnum.DELIVERY_AT_START]: 'Заказ готовится к отправке получателю',
  [YandexDeliveryStatusEnum.DELIVERY_TRANSPORTATION]: 'Заказ выехал в пункт назначения',
  [YandexDeliveryStatusEnum.DELIVERY_ARRIVED_PICKUP_POINT]: 'Заказ доставлен в пункт назначения',
  [YandexDeliveryStatusEnum.DELIVERY_TRANSMITTED_TO_RECIPIENT]: 'Заказ выдан получателю',
  [YandexDeliveryStatusEnum.DELIVERY_STORAGE_PERIOD_EXPIRED]: 'Срок хранения заказа в точке выдачи истек',
  [YandexDeliveryStatusEnum.DELIVERY_STORAGE_PERIOD_EXTENDED]: 'Срок хранения заказа в точке выдачи продлен',
  [YandexDeliveryStatusEnum.CONFIRMATION_CODE_RECEIVED]: 'Получен код подтверждения заказа',
  [YandexDeliveryStatusEnum.PARTICULARLY_DELIVERED]: 'Заказ частично доставлен',
  [YandexDeliveryStatusEnum.DELIVERY_DELIVERED]: 'Заказ доставлен получателю',
  [YandexDeliveryStatusEnum.FINISHED]: 'Заказ подтвержден',
};
